### ISSUE TITLE
How to provide translations? [tools] 

### ISSUE THREAD

**Issue by InYourHead** [pastillilabs/translations#4]
Hello,
I can provide polish internationalization, but I need to know what kind of tools I need to create it. What development tools do I need to start?

**Comment by hhaveri** [comment]
Hi,

Minimally, for translation work, you only need a text editor. But you can also use Qt Linguist. Unfortunately there is no official standalone download / installation package for Qt Linguist (it comes bundled with Qt SDK).

Besides that, the whole process is quite manual. The steps are mentioned in the Volunteering section here: https://github.com/pastillilabs/translations

**Comment by InYourHead** [comment]
Thanks, I will create pull request soon.
